name: DBNet
base: ["config/icdar2015.yaml"]
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.6
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 2
  beta: 10
  ohem_ratio: 1.5    
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 100
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: ""
  finetune_checkpoint: "/kaggle/working/DB-/model_best.pth"
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /kaggle/working/DB-/train.txt
        img_mode: RGB
    loader:
      batch_size: 8
      shuffle: true
      pin_memory: true
      num_workers: 6
      collate_fn: ""
  validate:
    dataset:
      args:
        data_path:
          - /kaggle/working/DB-/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 896
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 6
      collate_fn: ICDARCollectFN
